analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.7724015
  brandStrength: 1
  lightness: 1
  brandColors:
    - '#396591'
    - '#C6E0E9'
    - '#16D8E0'
    - '#BD91E1'
    - '#2730C6'
  rhythmicContrast: 0.06810036
typography_spectrum: 0.6326165
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 1
favicon: null
name: Magic Camp
