name: Magic Camp
favicon: null
layout_spectrum: 0.12858497048728168
typography_spectrum: 0.6243334608152509
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.39259552164003253
  lightness: 0.032985921716317534
  saturation: 0.6478253160603344
  rhythmicContrast: 0.475859796628356
purpose: []
